name: Loanledger
options:
  bundleIdPrefix: com.shimondeitel.loanledger
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Loanledger:
    type: application
    platform: iOS
    sources:
      - path: Loanledger
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.loanledger
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Loanledger/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  LoanledgerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LoanledgerTests
      - path: Loanledger.storekit
    dependencies:
      - target: Loanledger
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.loanledger.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  LoanledgerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: LoanledgerUITests
    dependencies:
      - target: Loanledger
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.loanledger.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Loanledger:
    build:
      targets:
        Loanledger: all
        LoanledgerTests: [test]
        LoanledgerUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Loanledger.storekit
    test:
      config: Debug
      storeKitConfiguration: Loanledger.storekit
      targets:
        - LoanledgerTests
        - LoanledgerUITests
    archive:
      config: Release
